# Generated by Django 5.2.4 on 2025-08-03 00:54

import apps.dreams.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image from your computer', null=True, upload_to=apps.dreams.models.dream_image_upload_path)),
                ('image_url', models.URLField(blank=True, help_text='Or provide a URL to an image', max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=apps.dreams.models.dream_image_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dreams.dream')),
            ],
            options={
                'db_table': 'dream_images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['dream', 'order'], name='dream_image_dream_i_b36b1c_idx')],
            },
        ),
    ]
